// ========================== MAIN IMPORTS ========================== //
// Import core libraries and UI components for building the song card.
// Includes HeroUI components for layout, badges, buttons, modals, skeletons, and links,
// as well as React hooks for state management and media query detection.
import {
  Button,
  Card,
  Modal,
  ModalBackdrop,
  ModalContainer,
  ModalDialog,
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalHeading,
  Skeleton,
  useOverlayState,
} from "@heroui/react";
import { useEffect, useState } from "react"; // React hooks for local state and side effects

import { AppleMusicIcon, SpotifyIcon } from "./icons"; // Custom Spotify icon component
import PresaveButton from "./presaveButton";
import SmartImage, { type ImageLikeImport } from "./smartImage"; // Optimized image component with automatic loading

// ========================== INTERFACES ========================== //
// Props definition for CardSongExposer component
interface CardSongExposerProps {
  artworkAlt: string; // Alt text for the song artwork
  artworkSrc: ImageLikeImport; // URL/object generated by bundler for song artwork
  songTitle: string; // Song title
  songDescription: string; // Short description of the song
  songSpotifyLink: string; // External link to the song on Spotify
  songAppleMusicLink: string; // External link to the song on Apple Music
  preSaveMode: boolean; // Flag indicating if "pre-save" mode is active
  hyperfollowUrl?: string; // DistroKid hyperfollow URL for pre-save mode
  releaseDate: Date; // Release date, used to switch the pre-save CTA once the song is out
  kind: string; // Tipo di release mostrato come tag (es. "Singolo")
  year: number; // Anno di uscita mostrato accanto al tag
}

// ========================== COMPONENT: CardSongExposer ========================== //
// Displays a music track card with artwork, title, and description.
// Features an interactive hover preview and a detailed modal.
//
// - Supports "pre-save" mode with a "COMING SOON" badge.
// - Uses HeroUI components for responsive and consistent UI.
// - Includes an external link to the song on Spotify.
export default function CardSongExposer({
  artworkSrc,
  artworkAlt,
  songTitle,
  songDescription,
  songSpotifyLink,
  songAppleMusicLink,
  preSaveMode,
  hyperfollowUrl,
  releaseDate,
  kind,
  year,
}: CardSongExposerProps) {
  const [isLoaded, setIsLoaded] = useState(false); // Tracks artwork image loading state
  const modal = useOverlayState(); // Manages modal open/close state

  // Safety fallback: prevents an infinite skeleton on browsers that don't fire image events reliably.
  useEffect(() => {
    if (isLoaded) return;

    const timeout = window.setTimeout(() => setIsLoaded(true), 6000);

    return () => window.clearTimeout(timeout);
  }, [isLoaded]);

  const handleOpen = () => {
    modal.open(); // Wrapper function to open modal
  };

  return (
    <div>
      {/* Main clickable card */}
      <Card
        className="group flex flex-col gap-4 pb-5 pt-5 px-5 bg-white transition-colors duration-300 hover:bg-danger w-full shadow-lg rounded-3xl border border-default-100 cursor-pointer"
        role="button"
        tabIndex={0}
        onClick={() => handleOpen()}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            handleOpen();
          }
        }}
      >
        {/* Skeleton placeholder displayed until artwork image loads */}
        {!isLoaded && (
          <Skeleton className="absolute inset-0 rounded-lg">
            <div className="h-full w-full bg-default-300 rounded-lg" />
          </Skeleton>
        )}

        {/* Card content: artwork + overlay "coming soon" */}
        <div className="relative overflow-hidden rounded-2xl">
          <SmartImage
            alt={artworkAlt}
            className="rounded-2xl"
            sizes="320px"
            src={artworkSrc}
            style={{ aspectRatio: "1 / 1" }}
            width={300}
            onError={() => setIsLoaded(true)} // Avoid stuck skeleton on mobile decode failures
            onLoad={() => setIsLoaded(true)} // Hide skeleton once image is loaded
          />

          {/* Pre-save badge: pill con dot pulsante */}
          {preSaveMode && (
            <div className="absolute left-2.5 top-2.5 z-20 flex items-center gap-1.5 rounded-full bg-black/65 px-2.5 py-1 shadow-lg ring-1 ring-white/25 backdrop-blur-md">
              <span className="relative flex h-1.5 w-1.5">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-danger opacity-80" />
                <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-danger" />
              </span>
              <span className="text-[0.6rem] font-bold uppercase tracking-[0.18em] text-white">
                Coming soon
              </span>
            </div>
          )}
        </div>

        {/* Tag tipo · anno + titolo */}
        <div className="flex w-full flex-col items-center gap-1.5">
          <span className="inline-flex items-center rounded-full bg-danger/10 px-2.5 py-0.5 text-[0.6rem] font-bold uppercase tracking-[0.2em] text-danger transition-colors duration-300 group-hover:bg-white/20 group-hover:text-white">
            {kind} · {year}
          </span>
          <h3 className="w-full truncate text-center font-bold text-black transition-colors duration-300 group-hover:text-white">
            {songTitle}
          </h3>
        </div>
      </Card>

      {/* Modal displaying song details and Spotify link */}
      <Modal state={modal}>
        <ModalBackdrop isDismissable variant="blur">
          <ModalContainer
            className="flex items-center justify-center m-0! px-4 sm:px-6 w-full max-w-none"
            placement="center"
          >
            <ModalDialog className="bg-white text-black dark:bg-white! dark:text-black! p-4 rounded-2xl shadow-xl max-w-120 mx-auto">
              {/* Modal header: tag + titolo del brano */}
              <ModalHeader className="flex flex-col items-center gap-1.5 pb-1 pt-2">
                <span className="inline-flex items-center rounded-full bg-danger/10 px-3 py-1 text-[0.65rem] font-bold uppercase tracking-[0.2em] text-danger">
                  {kind} · {year}
                </span>
                <ModalHeading className="text-balance text-center font-display text-2xl md:text-3xl font-bold tracking-tight text-black">
                  {songTitle}
                </ModalHeading>
                <span className="h-0.5 w-10 rounded-full bg-danger/30" />
              </ModalHeader>

              {/* Modal body with song description */}
              <ModalBody>
                <p className="text-left font-medium whitespace-break-spaces">
                  {songDescription}
                </p>
              </ModalBody>

              {/* Modal footer with Spotify button */}
              <ModalFooter className="flex flex-col">
                {!preSaveMode && (
                  <div className="text-center">
                    <text className="text-neutral-500 text-sm">
                      Ascolta ora il brano
                    </text>
                  </div>
                )}
                <div className="flex flex-col md:flex-row gap-2 w-full md:justify-between md:items-stretch">
                  {preSaveMode ? (
                    <div className="flex-1 min-w-0 flex justify-center">
                      <PresaveButton
                        hyperfollowUrl={hyperfollowUrl ?? ""}
                        releaseDate={releaseDate}
                      />
                    </div>
                  ) : (
                    <>
                      {/* Spotify */}
                      <div className="flex-1 min-w-0">
                        <Button
                          fullWidth
                          aria-label="Vai al brano su Spotify"
                          className="min-w-0 bg-success text-white hover:bg-success/90"
                          variant="primary"
                          onPress={() =>
                            window.open(
                              songSpotifyLink,
                              "_blank",
                              "noopener,noreferrer",
                            )
                          }
                        >
                          <SpotifyIcon />
                          Spotify
                        </Button>
                      </div>

                      {/* Apple Music */}
                      <div className="flex-1 min-w-0">
                        <Button
                          fullWidth
                          aria-label="Vai al brano su Apple Music"
                          className="min-w-0"
                          variant="danger"
                          onPress={() =>
                            window.open(
                              songAppleMusicLink,
                              "_blank",
                              "noopener,noreferrer",
                            )
                          }
                        >
                          <AppleMusicIcon />
                          Apple Music
                        </Button>
                      </div>
                    </>
                  )}
                </div>
              </ModalFooter>
            </ModalDialog>
          </ModalContainer>
        </ModalBackdrop>
      </Modal>
    </div>
  );
}
