// ========================== MAIN IMPORTS ========================== //
// Import core libraries and UI components for building the song card.
// Includes HeroUI components for layout, badges, buttons, modals, skeletons, and links,
// as well as React hooks for state management and media query detection.
import {
  Button,
  Card,
  ModalBackdrop,
  ModalContainer,
  ModalDialog,
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalHeading,
  Skeleton,
  useOverlayState,
} from "@heroui/react";
import { useEffect, useState } from "react"; // React hooks for local state and side effects

import {
  AmazonMusicIcon,
  AppleMusicIcon,
  SpotifyIcon,
  YouTubeMusicIcon,
} from "./icons"; // Custom platform icon components
import PresaveButton from "./presaveButton";
import SmartImage, { type ImageLikeImport } from "./smartImage"; // Optimized image component with automatic loading

// ========================== INTERFACES ========================== //
// Props definition for CardSongExposer component
interface CardSongExposerProps {
  artworkAlt: string; // Alt text for the song artwork
  artworkSrc: ImageLikeImport; // URL/object generated by bundler for song artwork
  songTitle: string; // Song title
  songDescription: string; // Short description of the song
  songSpotifyLink: string; // External link to the song on Spotify
  songAppleMusicLink: string; // External link to the song on Apple Music
  songAmazonMusicLink: string; // External link to the song on Amazon Music
  songYouTubeMusicLink: string; // External link to the song on YouTube Music
  preSaveMode: boolean; // Flag indicating if "pre-save" mode is active
  hyperfollowUrl?: string; // DistroKid hyperfollow URL for pre-save mode
  releaseDate: Date; // Release date, used to switch the pre-save CTA once the song is out
  kind: string; // Tipo di release mostrato come tag (es. "Singolo")
  year: number; // Anno di uscita mostrato accanto al tag
}

function CloseIcon() {
  return (
    <svg
      aria-hidden="true"
      fill="none"
      height={18}
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      viewBox="0 0 24 24"
      width={18}
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

// ========================== COMPONENT: CardSongExposer ========================== //
// Displays a music track card with artwork, title, and description.
// Features an interactive hover preview and a detailed modal.
//
// - Supports "pre-save" mode with a "COMING SOON" badge.
// - Uses HeroUI components for responsive and consistent UI.
// - Includes an external link to the song on Spotify.
export default function CardSongExposer({
  artworkSrc,
  artworkAlt,
  songTitle,
  songDescription,
  songSpotifyLink,
  songAppleMusicLink,
  songAmazonMusicLink,
  songYouTubeMusicLink,
  preSaveMode,
  hyperfollowUrl,
  releaseDate,
  kind,
  year,
}: CardSongExposerProps) {
  const [isLoaded, setIsLoaded] = useState(false); // Tracks artwork image loading state
  const modal = useOverlayState(); // Manages modal open/close state

  // Safety fallback: prevents an infinite skeleton on browsers that don't fire image events reliably.
  useEffect(() => {
    if (isLoaded) return;

    const timeout = window.setTimeout(() => setIsLoaded(true), 6000);

    return () => window.clearTimeout(timeout);
  }, [isLoaded]);

  const handleOpen = () => {
    modal.open(); // Wrapper function to open modal
  };

  return (
    <div>
      {/* Main clickable card */}
      <Card
        className="group flex flex-col gap-4 pb-5 pt-5 px-5 bg-white transition-colors duration-300 hover:bg-danger w-full shadow-lg rounded-3xl border border-default-100 cursor-pointer"
        role="button"
        tabIndex={0}
        onClick={() => handleOpen()}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            handleOpen();
          }
        }}
      >
        {/* Skeleton placeholder displayed until artwork image loads */}
        {!isLoaded && (
          <Skeleton className="absolute inset-0 rounded-lg">
            <div className="h-full w-full bg-default-300 rounded-lg" />
          </Skeleton>
        )}

        {/* Card content: artwork + overlay "coming soon" */}
        <div className="relative overflow-hidden rounded-2xl">
          <SmartImage
            alt={artworkAlt}
            className="rounded-2xl"
            sizes="320px"
            src={artworkSrc}
            style={{ aspectRatio: "1 / 1" }}
            width={300}
            onError={() => setIsLoaded(true)} // Avoid stuck skeleton on mobile decode failures
            onLoad={() => setIsLoaded(true)} // Hide skeleton once image is loaded
          />

          {/* Pre-save badge: pill con dot pulsante */}
          {preSaveMode && (
            <div className="absolute left-2.5 top-2.5 z-20 flex items-center gap-1.5 rounded-full bg-black/65 px-2.5 py-1 shadow-lg ring-1 ring-white/25 backdrop-blur-md">
              <span className="relative flex h-1.5 w-1.5">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-danger opacity-80" />
                <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-danger" />
              </span>
              <span className="text-[0.6rem] font-bold uppercase tracking-[0.18em] text-white">
                Coming soon
              </span>
            </div>
          )}
        </div>

        {/* Tag tipo · anno + titolo */}
        <div className="flex w-full flex-col items-center gap-1.5">
          <span className="inline-flex items-center rounded-full bg-danger/10 px-2.5 py-0.5 text-[0.6rem] font-bold uppercase tracking-[0.2em] text-danger transition-colors duration-300 group-hover:bg-white/20 group-hover:text-white">
            {kind} · {year}
          </span>
          <h3 className="w-full truncate text-center font-bold text-black transition-colors duration-300 group-hover:text-white">
            {songTitle}
          </h3>
        </div>
      </Card>

      {/* Modal displaying song details and Spotify link */}
      <ModalBackdrop
        isDismissable
        isOpen={modal.isOpen}
        variant="blur"
        onOpenChange={modal.setOpen}
      >
        <ModalContainer
          className="flex items-center justify-center m-0! px-4 sm:px-6 w-full max-w-none"
          placement="center"
        >
          <ModalDialog className="relative bg-white text-black dark:bg-white! dark:text-black! p-4 rounded-2xl shadow-xl max-w-120 mx-auto">
            {/* Chiudi: X in alto a destra */}
            <button
              aria-label="Chiudi"
              className="absolute right-3 top-3 z-10 flex h-8 w-8 items-center justify-center rounded-full text-default-500 transition-colors hover:bg-default-100"
              type="button"
              onClick={() => modal.close()}
            >
              <CloseIcon />
            </button>

            {/* Modal header: tag + titolo del brano */}
            <ModalHeader className="flex flex-col items-center gap-1.5 pb-1 pt-2">
              <span className="inline-flex items-center rounded-full bg-danger/10 px-3 py-1 text-[0.65rem] font-bold uppercase tracking-[0.2em] text-danger">
                {kind} · {year}
              </span>
              <ModalHeading className="text-balance text-center font-display text-2xl md:text-3xl font-bold tracking-tight text-black">
                {songTitle}
              </ModalHeading>
              <span className="h-0.5 w-10 rounded-full bg-danger/30" />
            </ModalHeader>

            {/* Modal body with song description */}
            <ModalBody>
              <p className="text-left font-medium whitespace-break-spaces">
                {songDescription}
              </p>
            </ModalBody>

            {/* Modal footer with Spotify button */}
            <ModalFooter className="flex flex-col">
              {!preSaveMode && (
                <div className="text-center">
                  <p className="text-neutral-500 text-sm">
                    Ascolta ora il brano
                  </p>
                </div>
              )}
              <div className="w-full">
                {preSaveMode ? (
                  <div className="flex justify-center">
                    <PresaveButton
                      hyperfollowUrl={hyperfollowUrl ?? ""}
                      releaseDate={releaseDate}
                    />
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    {/* Spotify */}
                    <div className="flex-1 min-w-0">
                      <Button
                        fullWidth
                        aria-label="Vai al brano su Spotify"
                        className="rounded-xl min-w-0 bg-success text-white hover:bg-success/90"
                        variant="primary"
                        onPress={() =>
                          window.open(
                            songSpotifyLink,
                            "_blank",
                            "noopener,noreferrer",
                          )
                        }
                      >
                        <SpotifyIcon />
                        Spotify
                      </Button>
                    </div>

                    {/* Apple Music */}
                    <div className="flex-1 min-w-0">
                      <Button
                        fullWidth
                        aria-label="Vai al brano su Apple Music"
                        className="rounded-xl min-w-0"
                        variant="danger"
                        onPress={() =>
                          window.open(
                            songAppleMusicLink,
                            "_blank",
                            "noopener,noreferrer",
                          )
                        }
                      >
                        <AppleMusicIcon />
                        Apple Music
                      </Button>
                    </div>

                    {/* Amazon Music */}
                    {songAmazonMusicLink && (
                      <div className="flex-1 min-w-0">
                        <Button
                          fullWidth
                          aria-label="Vai al brano su Amazon Music"
                          className="rounded-xl min-w-0 bg-[#00A8E1] text-white hover:bg-[#00A8E1]/90"
                          variant="primary"
                          onPress={() =>
                            window.open(
                              songAmazonMusicLink,
                              "_blank",
                              "noopener,noreferrer",
                            )
                          }
                        >
                          <AmazonMusicIcon />
                          Amazon Music
                        </Button>
                      </div>
                    )}

                    {/* YouTube Music */}
                    {songYouTubeMusicLink && (
                      <div className="flex-1 min-w-0">
                        <Button
                          fullWidth
                          aria-label="Vai al brano su YouTube Music"
                          className="rounded-xl min-w-0 bg-[#FF0000] text-white hover:bg-[#FF0000]/90"
                          variant="primary"
                          onPress={() =>
                            window.open(
                              songYouTubeMusicLink,
                              "_blank",
                              "noopener,noreferrer",
                            )
                          }
                        >
                          <YouTubeMusicIcon />
                          YouTube Music
                        </Button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </ModalFooter>
          </ModalDialog>
        </ModalContainer>
      </ModalBackdrop>
    </div>
  );
}
