// Email HTML template functions — mirrors supabase/functions/_shared/email.ts
// Used by the admin page to preview emails before sending.

// PNG generated by: npm run generate-email-assets (uses sharp, committed to public/).
// Gmail strips inline SVG — hosted PNGs are the only reliable cross-client solution.
// In dev: relative paths served by Vite from public/. In prod: absolute lacco.it URLs for email clients.
// header-email.png composites waves + logo into a single image — avoids position:absolute
// which many email clients ignore, causing waves and logo to render sequentially.
const _base = import.meta.env.PROD ? "https://lacco.it" : "";
const HEADER_IMG = `<img class="header-img" src="${_base}/header-email.png" width="520" height="128" alt="Lacco" style="display:block;width:100%;height:auto;border:0;">`;

function baseTemplate(
  content: string,
  opts?: { unsubscribeUrl?: string; transactional?: boolean },
): string {
  const signature = opts?.transactional
    ? ""
    : `<p class="email-text" style="margin:24px 0 0;font-size:15px;color:#333;line-height:1.7;">A presto,<br/><strong style="color:#F31260;">Lacco</strong></p>`;

  const footerContent = opts?.transactional
    ? `<p class="footer-text" style="margin:0;font-size:12px;color:#555;line-height:1.5;">
            Se non hai richiesto tu questo accesso, ignora questa email.
          </p>`
    : `<p class="footer-text" style="margin:0;font-size:12px;color:#555;line-height:1.5;">
            Hai ricevuto questa email perché sei iscritto alla newsletter di Lacco.
          </p>
          ${opts?.unsubscribeUrl ? `<p class="footer-link" style="margin:12px 0 0;font-size:11px;color:#555;">
            <a href="${opts.unsubscribeUrl}" style="color:#555;text-decoration:underline;">
              Disiscriviti dalla newsletter
            </a>
          </p>` : ""}`;

  return `<!DOCTYPE html>
<html lang="it" style="color-scheme:light dark;">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<meta name="color-scheme" content="light dark"/>
<meta name="supported-color-schemes" content="light dark"/>
<title>Lacco</title>
<style>
:root{color-scheme:light dark;}
.rte-body p{margin:0 0 16px;font-size:16px;color:#333;line-height:1.7;}
.rte-body p:last-child{margin-bottom:0;}
.rte-body ul,.rte-body ol{margin:0 0 16px;padding-left:24px;}
.rte-body li{font-size:16px;color:#333;line-height:1.7;margin-bottom:4px;}
@media (prefers-color-scheme:dark){
  body,.email-outer{background-color:#111111 !important;color:#e5e5ea !important;}
  .email-card{background-color:#1c1c1e !important;border-color:#2c2c2e !important;}
  .email-header,.email-body{background-color:#1c1c1e !important;}
  .email-footer{background-color:#1c1c1e !important;border-top-color:#2c2c2e !important;}
  .email-body p,.rte-body p,.rte-body li{color:#e5e5ea !important;}
  .footer-text{color:#8e8e93 !important;}
  .footer-link,.footer-link a{color:#8e8e93 !important;}
}
[data-ogsc] body,[data-ogsc] .email-outer{background-color:#111111 !important;}
[data-ogsc] .email-card,[data-ogsc] .email-header,[data-ogsc] .email-body,[data-ogsc] .email-footer{background-color:#1c1c1e !important;}
[data-ogsc] .email-body p,[data-ogsc] .rte-body p,[data-ogsc] .rte-body li{color:#e5e5ea !important;}
[data-ogsc] .footer-text,[data-ogsc] .footer-link,[data-ogsc] .footer-link a{color:#8e8e93 !important;}
</style>
</head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:system-ui,sans-serif;color:#333333;">
<table width="100%" class="email-outer" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:32px 16px;">
  <tr><td align="center">
    <table width="100%" class="email-card" bgcolor="#ffffff" style="max-width:520px;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e4e4e7;">
      <tr>
        <td class="email-header" bgcolor="#ffffff" style="padding:0;border-bottom:3px solid #F31260;background:#ffffff;line-height:0;font-size:0;">
          ${HEADER_IMG}
        </td>
      </tr>
      <tr>
        <td class="email-body" bgcolor="#ffffff" style="padding:32px;background:#ffffff;">
          ${content}
          ${signature}
        </td>
      </tr>
      <tr>
        <td class="email-footer" bgcolor="#ffffff" style="padding:16px 32px 24px;border-top:1px solid #e4e4e7;text-align:center;background:#ffffff;">
          ${footerContent}
        </td>
      </tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
}

export function welcomeEmailHtml(
  firstName: string | undefined,
  unsubscribeUrl: string,
): string {
  const name = firstName?.trim();
  const greeting = name
    ? `<p style="margin:0 0 16px;font-size:16px;color:#111;line-height:1.6;">Ciao ${name}!</p>`
    : "";

  return baseTemplate(
    `
    ${greeting}
    <p style="margin:0;font-size:16px;color:#333;line-height:1.6;">
      Benvenuto in famiglia!<br/>
      Sarai la prima persona a sapere delle novità di Lacco — nuove uscite, anteprime e aggiornamenti arriveranno direttamente qui.
    </p>
  `,
    { unsubscribeUrl },
  );
}

export function broadcastEmailHtml(opts: {
  body: string;
  imageUrl?: string;
  ctaText?: string;
  ctaUrl?: string;
  unsubscribeUrl: string;
  preview?: boolean;
}): string {
  const bodyHtml = opts.body;

  const imageSection = opts.imageUrl
    ? `<table width="100%" cellpadding="0" cellspacing="0" style="margin-top:24px;">
        <tr>
          <td align="center">
            <img src="${opts.imageUrl}" alt="" width="456"
                 style="display:block;width:100%;max-width:456px;height:auto;border-radius:8px;" />
          </td>
        </tr>
       </table>`
    : "";

  const ctaSection =
    opts.ctaText && opts.ctaUrl
      ? `<table width="100%" cellpadding="0" cellspacing="0" style="margin-top:24px;">
          <tr>
            <td align="center">
              <table cellpadding="0" cellspacing="0">
                <tr>
                  <td style="background:#F31260;border-radius:8px;">
                    <a href="${opts.ctaUrl}"
                       style="display:inline-block;padding:14px 28px;font-size:15px;font-weight:600;
                              color:#fff;text-decoration:none;letter-spacing:0.02em;">
                      ${opts.ctaText}
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
         </table>`
      : "";

  const greeting = opts.preview
    ? `<p style="margin:0 0 20px;font-size:16px;color:#111;line-height:1.6;">Ciao <span style="color:#F31260;">[Nome destinatario]</span>,</p>`
    : `<p style="margin:0 0 20px;font-size:16px;color:#111;line-height:1.6;">Ciao {{{contact.first_name|}}},</p>`;

  return baseTemplate(
    `${greeting}<div class="rte-body" style="font-size:16px;color:#333;line-height:1.7;">${bodyHtml}</div>${imageSection}${ctaSection}`,
    { unsubscribeUrl: opts.unsubscribeUrl },
  );
}
